nom.societe = AIRE
menu.accueil = Home
menu.contact = Contact us
presentation = Presentation
motsParPage = 70
objectif = objective
titre.haut = ACTING FOR IMPROVING
titre.bat = RURAL ENVIRONMENT
a.propos = Who are we
text.vert.haut = Acting for improving
text.vert.bas = Rural environnement
activites = Our activities
domaines = Our Domain
aire.company = Aire 2024 Company, Inc
text.donate = FOR CONSERVING AND RESTORING ECOSYSTEM
donate = Donate 