nom.societe = AIRE
menu.accueil = Accueil
menu.contact = Nous contacter
presentation = Presentation
motsParPage = 70
objectif = Objectif
titre.haut = ACTING FOR IMPROVING
titre.bat = RURAL ENVIRONMENT
a.propos = Qui somme nous
text.vert.haut = Acting for improving
text.vert.bas = Rural environnement
activites = Nos activités
domaines = Nos Domaine
aire.company = Aire 2024 Company, Inc
text.donate = FOR CONSERVING AND RESTORING ECOSYSTEM
donate = Donate 